CREATE TABLE [Levels] (
	ID int PRIMARY KEY IDENTITY NOT NULL,
	SkillID int NOT NULL,
	LevelName nvarchar(255) NOT NULL,
	UNIQUE(ID)
)
GO
ALTER TABLE [Levels]
WITH CHECK ADD CONSTRAINT FK_Levels_Skills FOREIGN KEY(SkillID)
REFERENCES Skills (ID)