CREATE TABLE [SkillMaps] (
	ID int PRIMARY KEY IDENTITY NOT NULL,
	SkillID int NOT NULL,
	LevelID int NOT NULL,
	UNIQUE(ID)
)
GO
AlTER TABLE [SkillMaps]
WITH CHECK ADD CONSTRAINT FK_SkillMaps_Levels FOREIGN KEY(LevelID)
REFERENCES Levels (ID)
GO
ALTER TABLE [SkillMaps]
WITH CHECK ADD CONSTRAINT FK_SkillMaps_Skills FOREIGN KEY(SkillID)
REFERENCES Skills (ID)